### ISSUE TITLE
[DISCUSSION] Using SQLITE rather than requiring postgres

### ISSUE THREAD

**Issue by RichyHBM** [Palleri/DCW#2]
This was more for a discussion than an issue, but would using sqlite be a smaller requirement rather than postgres given there shouldn't be too huge of a simultaneous usage of the app?

**Comment by Palleri** [comment]
Hi, I tried to use the sqlite in the beginning. But, The exporter
connecting to the database and inserting its values from dockcheck.
Sqlite does not support network based connections unfortunately.
