### ISSUE TITLE
Can it monitor docker via http proxy instead of docker.sock?

### ISSUE THREAD

**Issue by alpe12** [Palleri/DCW#8]
I want to use it behind [docker-socket-proxy](https://github.com/tecnativa/docker-socket-proxy/pkgs/container/docker-socket-proxy) for extra safety.

**Comment by Palleri** [comment]
Hi, I've thought about that. I have not test it, but it should work. But DCW is build with docker.sock in mind. But you could try.

**Comment by Palleri** [comment]
Sorry I accidentally closed the post.

**Comment by alpe12** [comment]
> Hi, I've thought about that. I have not test it, but it should work. But DCW is build with docker.sock in mind. But you could try.

@Palleri 
How? What I need to change?
On whats-up-docker I add this environment variable:
`WUD_WATCHER_Docker_HOST=dockerproxy`
Where "dockerproxy" is the name of the container for dockerproxy.

**Comment by alpe12** [comment]
@Palleri 
So..?

**Comment by Palleri** [comment]
Hi, sorry I've been offline for a longer time.

I dont think this version of DCW support this. Maybe I will take a look at it in the future. 
Please feel free to test and if you come up with a solution please let me know.
